# Generated by Django 4.1.7 on 2023-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0002_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumb_trailers'),
        ),
    ]
